# Netlify가 직접 빌드를 수행하는 경우에 동작(Github Actions에서 동작 x)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"