name: Build and Deploy to Netlify
on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            
            - name: Install dependencies
              run: npm install
            
            - name: Build project
              run: npm run build
              env:
                VITE_YOUTUBE_PLAYLIST_URL: ${{ secrets.VITE_YOUTUBE_PLAYLIST_URL }}
                VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL}}
                VITE_KAKAO_MAP_APP_KEY: ${{secrets.VITE_KAKAO_MAP_APP_KEY}}
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/

    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v2.0
              with:
                publish-dir: './dist'
                production-branch: develop
                github-token: ${{ secrets.GITHUB_TOKEN }}
                deploy-message: "🚀 [Deploy] ${{ github.head_ref || github.ref_name }}: ${{ github.event.head_commit.message }}"
                enable-pull-request-comment: true
                enable-commit-comment: true
                overwrites-pull-request-comment: true
              env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}